#!/bin/bash

# Suppress background job termination logs ("Killed...") to keep terminal clean
set +m

# ==========================================================
# DIRECTORY CONFIGURATION
# ==========================================================
PYTHON_WORKDIR=$(pwd)
NS3_WORKDIR="/home/shreyas/Desktop/ns-3-dev"

# Safe cleanup if the user aborts the bash script early (Ctrl+C)
cleanup() {
    echo ""
    echo "🛑 Script interrupted manually. Force killing background processes..."
    kill -9 $TWIN_PID $EDGE_PID 2>/dev/null
    pkill -9 -x "python3" 2>/dev/null
    exit 1
}
trap cleanup SIGINT

echo "🧹 Executing environment pre-clean to guarantee available ports..."
# Target specific background tasks safely without interrupting this script runner
pkill -9 -f "digital_twin.py" 2>/dev/null
pkill -9 -f "edge_node.py" 2>/dev/null
sleep 1

# Define scenarios to evaluate
SCENARIOS=("Scenario_A" "Scenario_B" "Scenario_C")

for SCENARIO in "${SCENARIOS[@]}"
do
    echo "=========================================================="
    echo "🚀 Starting Automated Evaluation for: $SCENARIO"
    echo "=========================================================="

    # Ensure we are in the Python directory
    cd "$PYTHON_WORKDIR" || exit 1

    # 1. Clear out historical test data for this specific scenario to prevent false positives
    rm -f "telemetry_${SCENARIO}.csv"

    # 2. Start the Digital Twin Server in the background
    python3 digital_twin.py "$SCENARIO" &
    TWIN_PID=$!
    
    # 3. Start the Edge Node in the background
    python3 edge_node.py "$SCENARIO" &
    EDGE_PID=$!

    # Give sockets and hardware initialization a brief moment to bind safely
    sleep 2

    # 4. Launch the NS-3 Network Simulation
    echo "🌐 Navigating to ns-3 workspace and launching simulation..."
    cd "$NS3_WORKDIR" || { echo "❌ Error: Could not find ns-3 directory at $NS3_WORKDIR"; exit 1; }
    
    # FIX: Pass the target and parameters cleanly
    ./ns3 run scratch/anasta_sim -- --scenario=$SCENARIO

    # Return to the Python workspace
    cd "$PYTHON_WORKDIR" || exit 1

    # 5. Gracefully terminate background Python threads using their exact PIDs
    echo "🛑 Stopping background Python applications..."
    kill -INT $TWIN_PID 2>/dev/null
    kill -INT $EDGE_PID 2>/dev/null
    sleep 3
    
    # Precise isolation: Hard-kill ONLY the exact PIDs assigned to this iteration loop
    kill -9 $TWIN_PID 2>/dev/null
    kill -9 $EDGE_PID 2>/dev/null

    # 6. Data Processing & Isolation
    # FIX: Checked filename targets the scenario-based name generated by digital_twin.py
    EXPECTED_CSV="telemetry_${SCENARIO}.csv"
    
    if [ -f "$EXPECTED_CSV" ]; then
        echo "📊 Telemetry data verified for $SCENARIO -> ($EXPECTED_CSV)"
        echo "📈 Rendering publication plots..."
        python3 plot.py
        echo "💾 Raw telemetry log successfully verified and preserved."
    else
        echo "⚠️ Error: Expected output file '$EXPECTED_CSV' was not detected!"
        echo "   Please check if digital_twin.py threw an unhandled exception."
    fi
    
    echo "=========================================================="
    echo "Done with $SCENARIO. Transitioning to next test cycle..."
    echo ""
done

# Restore default shell job settings
set -m

echo "=========================================================="
echo "✅ All Core Scenarios Executed and Plotted Successfully!"
echo "📂 High-quality evaluation assets generated inside workspace."
echo "=========================================================="